version: "2.1"
services:
  rdesktop:
    image: donswanson/kali-headful
    container_name: kali
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock #optional
      - ./data:/home/kali #optional
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
    ports:
      - 3389:3389
      - 2222:22


